// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8b5hz9E7fDjH4wFB4B_ftFP3IvLytLt0',
    appId: '1:309007840772:web:e79a1b4fb8fdf3c93b6751',
    messagingSenderId: '309007840772',
    projectId: 'sam-app01-flutter',
    authDomain: 'sam-app01-flutter.firebaseapp.com',
    storageBucket: 'sam-app01-flutter.appspot.com',
    measurementId: 'G-4WB1968VFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuiHGmD7sZ35tP3x_XwGc0MlT75AfxpDo',
    appId: '1:309007840772:android:35edbe92cdb6d6153b6751',
    messagingSenderId: '309007840772',
    projectId: 'sam-app01-flutter',
    storageBucket: 'sam-app01-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJvA7Bps6RssepxmPRxvzH8YCaBR1i2fI',
    appId: '1:309007840772:ios:97cf805614fcce1b3b6751',
    messagingSenderId: '309007840772',
    projectId: 'sam-app01-flutter',
    storageBucket: 'sam-app01-flutter.appspot.com',
    iosBundleId: 'com.test.myapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJvA7Bps6RssepxmPRxvzH8YCaBR1i2fI',
    appId: '1:309007840772:ios:f2aae914b85407833b6751',
    messagingSenderId: '309007840772',
    projectId: 'sam-app01-flutter',
    storageBucket: 'sam-app01-flutter.appspot.com',
    iosBundleId: 'com.test.myapp1.RunnerTests',
  );
}
